on:
  schedule:
    - cron: 0 0,12,14 * * *
  push:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: sudo apt-get -qq update && sudo apt-get -yqq install --no-install-recommends ffmpeg fonts-noto-cjk
      - run: yarn add puppeteer
      - run: node main.mjs
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PROXY_SERVER: ${{ secrets.PROXY_SERVER }}
      - uses: actions/upload-artifact@v4
        with:
          path: recording.webm
      - name: Send PushPlus Notification
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            TITLE="VPS自动续期成功🎉"
            CONTENT="Xserver VPS 自动续期脚本运行成功。"
          else
            TITLE="VPS自动续期失败❌"
            CONTENT="Xserver VPS 自动续期脚本运行失败，请去 GitHub Actions 查看具体报错日志。"
          fi
          curl -s -X POST "https://www.pushplus.plus/send" \
            -d "token=${{ secrets.PUSHPLUS_TOKEN }}" \
            --data-urlencode "title=${TITLE}" \
            --data-urlencode "content=${CONTENT}"
          curl -s "http://www.pushplus.plus/send?token=${{ secrets.PUSHPLUS_TOKEN }}&title=${TITLE}&content=${CONTENT}"
